DROP TABLE account CASCADE; 
DROP TABLE agent CASCADE;
DROP TABLE chat CASCADE;
DROP TABLE game CASCADE;
DROP TABLE game_copy CASCADE;
DROP TABLE hardware CASCADE;
DROP TABLE hardware_copy CASCADE;
DROP TABLE solution CASCADE;
DROP TABLE ticket CASCADE;
DROP TABLE account_issues CASCADE;
DROP TABLE billing CASCADE;
DROP TABLE hardware_repair CASCADE; 
DROP TABLE troubleshooting CASCADE;
DROP TABLE answered_by CASCADE;

